### PR TITLE
fix: explicitly convert string to UTF-8 byte array

### LINKED ISSUE #35: URLHelper is calling platform dependent String.getBytes()
URLHelper is calling platform dependent String.getBytes() here:
```
private String encodeBase64(String str) {
	byte[] stringBytes = str.getBytes();
```
But as far as I know base64 encoding for urls require UTF-8 to be used and should be specified explicitly here.

Running this example program:
```
public class ImgixExample {
    public static void main(String[] args) {
        System.out.println("Default charset: " + Charset.defaultCharset());
        URLBuilder builder = new URLBuilder("demos.imgix.net");
        Map<String, String> params = new HashMap<String, String>();
        params.put("m64", "http://demos.imgix.net/bridge.png?ixlib=java-2.1.0");
        System.out.println(builder.createURL("bridge.png", params));
    }
}
```

with -Dfile.encoding=UTF-8 and -Dfile.encoding=UTF-32 respectively demonstrates the problem:

```
Default charset: UTF-8
http://demos.imgix.net/bridge.png?ixlib=java-2.1.0&m64=aHR0cDovL2RlbW9zLmltZ2l4Lm5ldC9icmlkZ2UucG5nP2l4bGliPWphdmEtMi4xLjA
```

```
Default charset: UTF-32
http://demos.imgix.net/bridge.png?ixlib=java-2.1.0&m64=�������������������������������������������������������������������
```

### PR DESCRIPTION
**Pull request by sherwinski**
This PR explicitly converts a query parameter value to UTF-8 before encoding the value to base64. Without specifying the encoding scheme explicitly, the behavior of `getBytes()` and the subsequent `String` instantiation would be platform dependent, which can result in incorrectly-encoded values. By specifying `UTF-8`, we can ensure the results regardless of the default charset of the calling system.
Fixes #35

### CODE REVIEW

**Comment by sherwinski** [comment]
Hey @spand, I have a fix here for the encoding issue you opened earlier. Feel free to take a look and let me know what you think. Thanks!

File: src/main/java/com/imgix/URLHelper.java [hunk 1]
```diff
@@ -64,8 +64,14 @@ public void deleteParameter(String key) {
 	}
 
 	private String encodeBase64(String str) {
-		byte[] stringBytes = str.getBytes();
-		String b64EncodedString = new String(Base64.getEncoder().encode(stringBytes));
+		byte[] stringBytes = new byte[0];
```
Comment (nico256) [inline src/main/java/com/imgix/URLHelper.java]: just declare this variable inside the `try` block, or inline the variable. No point in allocating an array of length zero and then immediately throwing it away on line 71.

**Review by nico256 — APPROVED** [review]

**Comment by spand** [comment]
Looks good !
